### ISSUE TITLE
missing 116mm paper size

### ISSUE THREAD

**Issue by ghost** [rezins/datecs_printer#3]
Hello,

Thank you for your work! This is project is very big help for me!

Could you add mm116 enum item to DatecsPaper?

Thank you!

Tamas

**Comment by rezins** [comment]
Is paper mm116 has 48 character per line in a row? if say so, I think actually you can use mm80.
here the information from official website (DPP-450 Receipt)
![image](https://user-images.githubusercontent.com/18201980/178489051-34a0d4e3-d475-4752-b56c-c4b89c2e16f3.png)
please tell me if mm116 has more then 48 character per line

**Comment by ghost** [comment]
I patched the code and try tried it previously. 69 characters (maybe 68 or 64 better) was visible.

**Comment by rezins** [comment]
@Mato70 I've already enhance for paper sized 116mm. I'm use 64 characters per line for 116mm so I can easily divide with 8 (row per line).  Checkout datecs_printer 0.05. 
Sorry I'm kind a busy last week. Maybe that can help you.
