### ISSUE TITLE
partialy printed page

### ISSUE THREAD

**Issue by ghost** [rezins/datecs_printer#4]
Sometimes the whole page not printed fully, only a half or less or more. Is there any workarround or possible to fix it?

**Comment by rezins** [comment]
Hmm, can you record when you printed not fully ? I'm actually had no problem with print long receipt.
you can send to my email or upload on online video sharing platform or something

**Comment by ghost** [comment]
We use about 6 printers, mine is usualy works normally, but the others print multiple times or only partially.

**Comment by ghost** [comment]
I try it now and it prints 6 times... It is so strange. For the truth, I have to say I changed the jar file to a newer one.

**Comment by rezins** [comment]
I'm sorry Mato, I can't change the jar file into a new one, because I don't have datecs printer device any more. when I develop this plugin my customer lend me a datecs device but when I finish develop I give it back. So I cant change the android section cz it is too risk.

**Comment by rezins** [comment]
but when print 6 times it's quite wired, have you trace when execute script `await DatecsPrinter.printText(ticket);` doesn't hit six times?
