### ISSUE TITLE
Verifone x990 PDQ Device (40 mm paper roll) support

### ISSUE THREAD

**Issue by r-durao-pvotal** [rezins/datecs_printer#6]
Hello!

We are thinking of using this package in one of our projects and I was wondering if it supports printers with 18lps and 40 mm paper roll?

Thanks in advance

**Comment by rezins** [comment]
you mean : High-speed thermal printer, max. speed: 90mm/s (18lps) Paper width: 58mm, Paper roll diameter: 40mm?

**Comment by r-durao-pvotal** [comment]
Not quite sure, because the [PDQ device info page](https://www.verifone.com/en/in/devices/integrated-pos/x990) doesn't go into that much detail, but I think your description is accurate

**Comment by rezins** [comment]
Have you tried run example project? did it work with this package?

**Comment by r-durao-pvotal** [comment]
I don't have access to the hardware just yet, but once I do I will let you know

**Comment by rezins** [comment]
I see, but I never use your mentioned device, so I cannot say this package will support with your printer

**Comment by r-durao-pvotal** [comment]
If you don't mind, I'll rename the issue and keep it open

**Comment by r-durao-pvotal** [comment]
@rezins your example does not seem to detect the printer that this PDQ device has. does this only work for bluetooth printers?
