### ISSUE TITLE
Its possible print images on full page?

### ISSUE THREAD

**Issue by riberman** [rezins/datecs_printer#7]
When i use the DatecsGenerate like:  
`ByteData bytes = await rootBundle.load('assets/empty-box.png');
      var buffer = bytes.buffer;
      var m = base64Encode(Uint8List.view(buffer));

      generate.image(m);`  
The image is printed in center of page and the size this image is the same independent the resolution of image file,   
Is there any way to format the size of the image on the printout?  
  
  
I'm trying to print a PDF converted to an image, but the resolution is too small on the printout.

**Comment by rezins** [comment]
When I build this package, the image only purpose for company logo so I resize for 300x300 and center align. But you can fork and modify in android java file line 168
